### ISSUE TITLE
Tomahawk music player does not start

### ISSUE THREAD

**Issue by ManuelPimienta** [Antergos/antergos-packages#133]
Install from the console and not start
~$ tomahawk
tomahawk: error while loading shared libraries: libboost_filesystem.so.1.60.0: cannot open shared object file: No such file or directory

**Comment by f-fouad** [comment]
Same problem here.
The version installed on system is 1.62.0.
I tried creating a symlink to the new version but the same error message persists.
/usr/lib/libboost_filesystem.so.1.60.0 -> /usr/lib/libboost_filesystem.so.1.62.0

**Comment by slacka** [comment]
```
$ yaourt -S tomahawk
$ tomahawk
```

Played a few songs, no issues.

**Comment by karasu** [comment]
Yep, it also works here. If I recall, tomahawk package needed an update.
Thanks for reporting it!
Closing.

**Comment by postadelmaga** [comment]
it is happening again to me on Antergos:
```
$ tomahawk
tomahawk: error while loading shared libraries: libboost_filesystem.so.1.62.0: cannot open shared object file: No such file or directory

```

**Comment by stratus-ss** [comment]
@karasu I tried to go in to the build service and fix this but I can no longer log in

**Comment by killajoe** [comment]
yaourt -S tomahawk
resolving dependencies...
warning: cannot resolve "quazip-qt5", a dependency of "tomahawk"
:: The following package cannot be upgraded due to unresolvable dependencies:
      tomahawk

error: target not found: quazip-qt5

**Comment by karasu** [comment]
@stratus-ss I have no powers there, you'll have to ask @lots0logs 

Thanks @killajoe it seems quazip-qt5 has been removed from "official" arch. Now there's quazip in AUR.

This https://github.com/Antergos/antergos-packages/commit/2148cb94cb3774c74a2c7193760502eab248ac96 and https://github.com/Antergos/antergos-packages/commit/7bb45f14d411985b67a1688062f31a2203866e1a should fix it

**Comment by slacka** [comment]
I was also getting the 'ibboost_filesystem.so.1.62.0: cannot open shared object file: No such file' error, but it's been fixed with the latest update. Thanks @karasu

**Comment by chris968** [comment]
The problem is still present with the current version.

`tomahawk: error while loading shared libraries: libboost_system.so.1.63.0: cannot open shared object file: No such file or directory`

It seems that the current version of libboost was 1.64.0.

**Comment by killajoe** [comment]
actual=extra/boost-libs 1.64.0-1
                                     
/usr/lib/libboost_filesystem.so.1.64.0
/usr/lib/libboost_system.so.1.64.0
