### ISSUE TITLE
Create a dummy package: xorg-mkfontdir

### ISSUE THREAD

**Issue by manuel-192** [Antergos/antergos-packages#436]
Currently Antergos cannot be installed without a workaround of deleting package xorg-mkfontdir from packages.xml. Since people new to Antergos do not know about the workaround, another workaround is to create a dummy package for xorg-mkfontdir and make it available on Antergos mirrors.

AFAIK a dummy package only requires file .PKGINFO with minimal contents, so it is very easy to create.

**Comment by killajoe** [comment]
https://github.com/Antergos/Cnchi/pull/1130

**Comment by lots0logs** [comment]
We removed the package from packages.xml on github. Cnchi gets its packages.xml from github. Thus the issue should now be resolved. Please let me know if that's not the case.

**Comment by lots0logs** [comment]
Actually I found the problem. We were serving the file form master branch. Its fixed now, see: http://install.antergos.com

**Comment by manuel-192** [comment]
Jus a minute ago I tried installing and the problem still exists.

**Comment by manuel-192** [comment]
> Actually I found the problem. We were serving the file form master branch. Its fixed now, see: http://install.antergos.com

No, the installer gets it from https://raw.githubusercontent.com/Antergos/Cnchi/master/data/packages.xml

**Comment by killajoe** [comment]
and what is about:
https://github.com/Antergos/Cnchi/blob/0.16.x/utils/download_package_list.py
having:
`packages_xml = urllib.request.urlopen('http://install.antergos.com/packages-0.8.xml')`
what links to:
https://raw.githubusercontent.com/Antergos/Cnchi/0.16.x/data/packages.xml
![Bildschirmfoto vom 2019-03-13 15-52-11](https://user-images.githubusercontent.com/16797647/54289368-50dd9800-45a9-11e9-8150-a15594477b6f.png)

**Comment by lots0logs** [comment]
You were getting a cached version of the file. Seems the cache has updated now though. Let me know if you still have trouble.

**Comment by manuel-192** [comment]
Just now I tried installing, but the same error.
How can we avoid that cache?

**Comment by manuel-192** [comment]
OK, now the packages.xml file seems to work!
Just installed Antergos without any workaround.

**Comment by killajoe** [comment]
yes it is updated now
