### ISSUE TITLE
Gnome 3.32 Dash-to-dock broken

### ISSUE THREAD

**Issue by MaxXor** [Antergos/antergos-packages#441]

**Comment by karasu** [comment]
Please @MaxXor , provide more information. We cannot work with "broken".

**Comment by MaxXor** [comment]
It just needs an update to the [metadata version number](https://github.com/micheleg/dash-to-dock/blob/master/metadata.json), see here: https://github.com/micheleg/dash-to-dock/issues/907

**Comment by karasu** [comment]
Thanks, I think @lots0logs and others fixed it. I've just published it now. It will take a bit to update the mirrors.

**Comment by MaxXor** [comment]
It's still broken, the dock is now shown, but it's completely empty for me.

**Comment by MaxXor** [comment]
Seems like it still includes legacy code :/ https://gitlab.gnome.org/GNOME/gnome-shell/issues/1069

**Comment by killajoe** [comment]
AUR git version is the only one working here

**Comment by killajoe** [comment]
but as commented here:
https://github.com/micheleg/dash-to-dock/issues/907
version 66 is into https://aur.archlinux.org/packages/gnome-shell-extension-dash-to-dock
and this is working too..

**Comment by MaxXor** [comment]
@karasu  Please update, [version 66](https://github.com/micheleg/dash-to-dock/releases/tag/extensions.gnome.org-v66) has been released.

**Comment by karasu** [comment]
Doing it right now. Please be patient...

**Comment by karasu** [comment]
@killajoe @MaxXor OK, it's in the build server. I cannot test it as I'm at work atm.

Please, tell me if it works for you.

Thanks!

**Comment by MaxXor** [comment]
Works, thanks a lot!

**Comment by killajoe** [comment]
indeed v-66 is working as it should! thanks @karasu !!
